### ISSUE TITLE
デバイスHW構成確定

### ISSUE THREAD

**Issue by nobrooklyn** [tutertlob/rny-1#3]
デバイスのHW構成を確定する。

**Comment by Reiji-Nishiyama** [comment]
確定。パーツ選定と調達も完了。
[HW構成](https://drive.google.com/file/d/1pJeE0gdqLrCBD9APOin-uxu14GQ2CYqlFKCQOJcCA4Xo_AmGtXVbuxiCLKNNN-jiByrNHU9AhcBPkgYw/view?usp=sharing)
[パーツリスト](https://docs.google.com/spreadsheets/d/1ASKe4Y24WkBbAil3ncN_udZZaydx2GNa1yCTuJ-e_gA/edit?usp=sharing)

**Comment by Reiji-Nishiyama** [comment]
This commit fixes #3

**Comment by Reiji-Nishiyama** [comment]
HW構成は一旦[これで](https://github.com/tutertlob/rny-1/tree/master/Mailbox_sender)Fix。
