### ISSUE TITLE
デバイスtoGWのプロトコル設計

### ISSUE THREAD

**Issue by nobrooklyn** [tutertlob/rny-1#7]
デバイスからGWに飛ばすメッセージプロトコルの設計。
既成の6LowPANを使うか、独自実装とするか。
画像データを扱うため、分割再結合などの考慮が必要。

**Comment by Reiji-Nishiyama** [comment]
特定小電力無線モジュールIM920を使ったメッセージプロトコル設計済み。
詳細は[こちら](https://github.com/tutertlob/im920-arduino)。
ArduinoとJava用ライブラリを作成。
* Arduino用は[こちら](https://github.com/tutertlob/im920-arduino)
* Java用は[こちら](https://github.com/tutertlob/im920-java)
